apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend-api
data:
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPIC: "energy_data"
  PORT: "3000"
  RECENT_MESSAGES_LIMIT: "1000"
